### ISSUE TITLE
Error from auth.py after completing the localhost:8080 callback

### ISSUE THREAD

**Issue by timrhaynes** [KTibow/pi-DriveUp#3]
When I run:

`sudo python auth.py`

and then successfully complete all of the browser screens, the final redirect to localhost:8080 results in an error from auth.py:

```
If a window doesn't pop up in the next few seconds, or if
this machine doesn't have an accesible web browser, copy and paste 
https://login.live.com/oauth20_authorize.srf?client_id=f41aa9e8-8e6c-4618-a5b5-87bf12c16d7e&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=wl.signin+wl.offline_access+onedrive.readwrite
 into your browser.
127.0.0.1 - - [04/Apr/2023 16:44:22] "GET /?code=M.R3_BL2.2.d3f4ad5b-dfd0-7e51-3721-e66d4100289d HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/trhaynes/pi-DriveUp/auth.py", line 44, in <module>
    client.auth_provider.authenticate(code, redirect_uri, client_secret)
  File "/usr/local/lib/python3.9/dist-packages/onedrivesdk/auth_provider.py", line 200, in authenticate
    response = self._http_provider.send(method="POST",
  File "/usr/local/lib/python3.9/dist-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python3.9/dist-packages/onedrivesdk/http_response.py", line 61, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_client
```

I note that there is no client information in the localhost:8080 redirect, and I have been very careful to paste in the client ID when asked for it:

![image](https://user-images.githubusercontent.com/24923033/229917304-c8403bc7-dfae-4b28-bbde-00e68faa3f0b.png)

Do you have any advice?
Thank you

**Comment by KTibow** [comment]
sadly the underlying sdk i use for onedrive is dead
this project isn't really maintained anymore so there won't be any future updates but you can always zip up what matters to you
